package fr.valoriatycoon.ranks;

public enum RankPromotionStatus {
    SUCCESS,
    MAXIMUM_RANK,
    NO_ACTIVE_ISLAND,
    INSUFFICIENT_MONEY,
    INSUFFICIENT_PLAYTIME,
    INSUFFICIENT_VANILLA_EXPERIENCE,
    INSUFFICIENT_QUESTS,
    INSUFFICIENT_TOOL_LEVELS,
    INSUFFICIENT_PROFESSION_LEVELS,
    STALE_RANK
}
